namespace DataPresentation
{
    partial class DataPresentation : System.Windows.Forms.Form // Partial class for the main form, derived from System.Windows.Forms.Form
    {
        /// <summary>
        /// Variable required by the Windows Forms designer.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Cleans up used resources.
        /// </summary>
        /// <param name="disposing">True if managed resources should be released; otherwise, False.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) // Checks whether resources should be released
            {
                components.Dispose(); // Releases managed resources
            }
            base.Dispose(disposing); // Calls the base method to release resources
        }

        #region Code generated by Windows Form Designer

        /// <summary>
        /// Method required for designer support. Do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            // Initialize component container
            components = new System.ComponentModel.Container();
            Label label1; // Label for patient code
                          // Binding to the data source for SensorBase objects
            sensorBaseBindingSource = new BindingSource(components);
            // ComboBox for selecting patient code when monitoring starts
            cbPatientCodeStart = new ComboBox();
            // Button for starting monitoring
            bStartPumping = new Button();
            // Button for stopping monitoring
            bStopPumping = new Button();
            // Second binding source for SensorBase objects
            sensorBaseBindingSource1 = new BindingSource(components);
            // DataGridView for displaying sensor data
            dgSensorBaseList = new DataGridView();
            // Column for displaying patient code
            patientCodeDataGridViewTextBoxColumn1 = new DataGridViewTextBoxColumn();
            // Column for displaying sensor type
            sensorTypeDataGridViewTextBoxColumn1 = new DataGridViewTextBoxColumn();
            // Column for displaying sensor value
            valueDataGridViewTextBoxColumn1 = new DataGridViewTextBoxColumn();
            // Column for displaying timestamp
            timestampDataGridViewTextBoxColumn1 = new DataGridViewTextBoxColumn();
            // TextBox for setting the timer period
            tbTimerPeriod = new TextBox();
            // Label describing the period TextBox
            label2 = new Label();
            // Additional label describing the period between samples
            label3 = new Label();
            // RichTextBox for displaying alarms
            richTextBox1 = new RichTextBox();
            // Label for the alarms area
            label4 = new Label();
            // ComboBox for filtering data by patient
            cbFilterPatient = new ComboBox();
            // Control for selecting the filter date
            dtpFilterDate = new DateTimePicker();
            // Button for filtering and displaying selected data
            bFilter = new Button();
            // GroupBox for the data filtering section
            groupBoxFiltering = new GroupBox();
            // Button for displaying received data
            bReceived = new Button();
            // GroupBox for the data management section (start/stop, period, etc.)
            groupBoxData = new GroupBox();
            // RadioButton for the option to send data over TCP/IP
            radioButton1 = new RadioButton();
            // RadioButton for using the local channel option
            radioButton2 = new RadioButton();
            // TextBox for entering server IP address
            textBox1 = new TextBox();
            // Label indicating the server IP address
            label5 = new Label();
            // GroupBox for communication channel options
            groupBox1 = new GroupBox();
            // Initialize or reinitialize designer components
            label1 = new Label();
            ((System.ComponentModel.ISupportInitialize)sensorBaseBindingSource).BeginInit(); // Begins initialization of the data source
            ((System.ComponentModel.ISupportInitialize)sensorBaseBindingSource1).BeginInit(); // Begins initialization of the second data source
            ((System.ComponentModel.ISupportInitialize)dgSensorBaseList).BeginInit(); // Begins initialization of the DataGridView
            groupBoxFiltering.SuspendLayout(); // Suspends layout for the filtering GroupBox
            groupBoxData.SuspendLayout(); // Suspends layout for the data GroupBox
            groupBox1.SuspendLayout(); // Suspends layout for the communication GroupBox
            SuspendLayout(); // Suspends the form general layout
                             // 
                             // Configure label1 (Patient Code)
                             // 
            label1.AutoSize = true; // Sets text auto-sizing
            label1.Location = new Point(6, 19); // Sets label location
            label1.Name = "label1"; // Unique name for label
            label1.Size = new Size(75, 15); // Label size
            label1.TabIndex = 6; // Tab index
            label1.Text = "Patient Code"; // Text displayed on label
            label1.Click += label1_Click; // Click event for label
                                          // 
                                          // Configure binding for sensorBase
                                          // 
            sensorBaseBindingSource.DataSource = typeof(SensorBase); // Sets data type for binding
                                                                     // 
                                                                     // Configure patient start ComboBox
                                                                     // 
            cbPatientCodeStart.FormattingEnabled = true; // Allows selection from a list
            cbPatientCodeStart.Location = new Point(6, 35); // Sets ComboBox location
            cbPatientCodeStart.Name = "cbPatientCodeStart"; // Unique name for ComboBox
            cbPatientCodeStart.Size = new Size(169, 23); // ComboBox size
            cbPatientCodeStart.TabIndex = 1; // Tab index
            cbPatientCodeStart.SelectedIndexChanged += cbPatientCodeStart_SelectedIndexChanged; // Selection changed event
                                                                                                // 
                                                                                                // Configure start monitoring button
                                                                                                // 
            bStartPumping.Location = new Point(198, 15); // Sets button location
            bStartPumping.Name = "bStartPumping"; // Unique name for button
            bStartPumping.Size = new Size(169, 43); // Button size
            bStartPumping.TabIndex = 2; // Tab index
            bStartPumping.Text = "Start Monitoring"; // Text displayed on button
            bStartPumping.UseVisualStyleBackColor = true; // Uses the default button style
            bStartPumping.Click += bStartPumping_Click; // Click event for button
                                                        // 
                                                        // Configure stop monitoring button
                                                        // 
            bStopPumping.Location = new Point(196, 72); // Sets button location
            bStopPumping.Name = "bStopPumping"; // Unique name for button
            bStopPumping.Size = new Size(169, 44); // Button size
            bStopPumping.TabIndex = 3; // Tab index
            bStopPumping.Text = "Stop Monitoring"; // Text displayed on button
            bStopPumping.UseVisualStyleBackColor = true; // Uses the default button style
            bStopPumping.Click += bStopPumping_Click; // Click event for button
                                                      // 
                                                      // Configure second binding source for sensorBase
                                                      // 
            sensorBaseBindingSource1.DataSource = typeof(SensorBase); // Sets data type for binding
                                                                      // 
                                                                      // Configure grid for displaying sensor data
                                                                      // 
            dgSensorBaseList.AutoGenerateColumns = false; // Disables automatic column generation
            dgSensorBaseList.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.AllCells; // Sets automatic column resizing
            dgSensorBaseList.AutoSizeRowsMode = DataGridViewAutoSizeRowsMode.AllCells; // Sets automatic row resizing
            dgSensorBaseList.BackgroundColor = SystemColors.ActiveCaptionText; // Sets background color
            dgSensorBaseList.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize; // Sets column header display mode
            dgSensorBaseList.Columns.AddRange(new DataGridViewColumn[] { patientCodeDataGridViewTextBoxColumn1, sensorTypeDataGridViewTextBoxColumn1, valueDataGridViewTextBoxColumn1, timestampDataGridViewTextBoxColumn1 }); // Adds columns to the grid
            dgSensorBaseList.DataSource = sensorBaseBindingSource; // Sets data source
            dgSensorBaseList.GridColor = SystemColors.MenuHighlight; // Sets grid color
            dgSensorBaseList.Location = new Point(2, 2); // Sets grid location
            dgSensorBaseList.Name = "dgSensorBaseList"; // Unique name for grid
            dgSensorBaseList.Size = new Size(472, 618); // Grid size
            dgSensorBaseList.StandardTab = true; // Enables tab navigation
            dgSensorBaseList.TabIndex = 4; // Tab index
            dgSensorBaseList.CellContentClick += dgSensorBaseList_CellContentClick; // Click event for grid cells
                                                                                    // 
                                                                                    // Configure patient code column in grid
                                                                                    // 
            patientCodeDataGridViewTextBoxColumn1.DataPropertyName = "PatientCode"; // Sets data binding property
            patientCodeDataGridViewTextBoxColumn1.HeaderText = "Patient"; // Text displayed in column header
            patientCodeDataGridViewTextBoxColumn1.Name = "patientCodeDataGridViewTextBoxColumn1"; // Unique name for column
            patientCodeDataGridViewTextBoxColumn1.ReadOnly = true; // Sets column as read-only
            patientCodeDataGridViewTextBoxColumn1.Width = 69; // Column width
                                                              // 
                                                              // Configure sensor type column in grid
                                                              // 
            sensorTypeDataGridViewTextBoxColumn1.DataPropertyName = "SensorType"; // Sets data binding property
            sensorTypeDataGridViewTextBoxColumn1.HeaderText = "Sensor"; // Text displayed in column header
            sensorTypeDataGridViewTextBoxColumn1.Name = "sensorTypeDataGridViewTextBoxColumn1"; // Unique name for column
            sensorTypeDataGridViewTextBoxColumn1.ReadOnly = true; // Sets column as read-only
            sensorTypeDataGridViewTextBoxColumn1.Width = 67; // Column width
                                                             // 
                                                             // Configure sensor value column in grid
                                                             // 
            valueDataGridViewTextBoxColumn1.DataPropertyName = "Value"; // Sets data binding property
            valueDataGridViewTextBoxColumn1.HeaderText = "Value"; // Text displayed in column header
            valueDataGridViewTextBoxColumn1.Name = "valueDataGridViewTextBoxColumn1"; // Unique name for column
            valueDataGridViewTextBoxColumn1.ReadOnly = true; // Sets column as read-only
            valueDataGridViewTextBoxColumn1.Width = 60; // Column width
                                                        // 
                                                        // Configure timestamp column in grid
                                                        // 
            timestampDataGridViewTextBoxColumn1.DataPropertyName = "Timestamp"; // Sets data binding property
            timestampDataGridViewTextBoxColumn1.HeaderText = "Timestamp"; // Text displayed in column header
            timestampDataGridViewTextBoxColumn1.Name = "timestampDataGridViewTextBoxColumn1"; // Unique name for column
            timestampDataGridViewTextBoxColumn1.ReadOnly = true; // Sets column as read-only
            timestampDataGridViewTextBoxColumn1.Width = 92; // Column width
                                                            // 
                                                            // Configure TextBox for timer period
                                                            // 
            tbTimerPeriod.Location = new Point(6, 93); // Sets TextBox location
            tbTimerPeriod.Name = "tbTimerPeriod"; // Unique name for TextBox
            tbTimerPeriod.Size = new Size(169, 23); // TextBox size
            tbTimerPeriod.TabIndex = 5; // Tab index
            tbTimerPeriod.TextChanged += tbTimerPeriod_TextChanged; // Text changed event
                                                                    // 
                                                                    // Configure label for time period
                                                                    // 
            label2.AutoSize = true; // Sets text auto-sizing
            label2.Location = new Point(7, 75); // Sets label location
            label2.Name = "label2"; // Unique name for label
            label2.Size = new Size(74, 15); // Label size
            label2.TabIndex = 7; // Tab index
            label2.Text = "Time period "; // Text displayed on label
            label2.Click += label2_Click; // Click event for label
                                          // 
                                          // Configure additional label for period between samples
                                          // 
            label3.AutoSize = true; // Sets text auto-sizing
            label3.Location = new Point(73, 75); // Sets label location
            label3.Name = "label3"; // Unique name for label
            label3.Size = new Size(98, 15); // Label size
            label3.TabIndex = 8; // Tab index
            label3.Text = "between samples"; // Text displayed on label
            label3.Click += label3_Click; // Click event for label
                                          // 
                                          // Configure RichTextBox for displaying alarms
                                          // 
            richTextBox1.Location = new Point(480, 163); // Sets RichTextBox location
            richTextBox1.Name = "richTextBox1"; // Unique name for RichTextBox
            richTextBox1.ScrollBars = RichTextBoxScrollBars.Vertical; // Enables vertical scrollbar
            richTextBox1.Size = new Size(378, 132); // RichTextBox size
            richTextBox1.TabIndex = 9; // Tab index
            richTextBox1.Text = ""; // Default text
                                    // 
                                    // Configure label for alarms area
                                    // 
            label4.AutoSize = true; // Sets text auto-sizing
            label4.Location = new Point(641, 145); // Sets label location
            label4.Name = "label4"; // Unique name for label
            label4.Size = new Size(44, 15); // Label size
            label4.TabIndex = 10; // Tab index
            label4.Text = "Alarms"; // Text displayed on label
                                    // 
                                    // Configure ComboBox for filtering by patient
                                    // 
            cbFilterPatient.FormattingEnabled = true; // Allows selection from a list
            cbFilterPatient.Location = new Point(6, 22); // Sets ComboBox location
            cbFilterPatient.Name = "cbFilterPatient"; // Unique name for ComboBox
            cbFilterPatient.Size = new Size(159, 23); // ComboBox size
            cbFilterPatient.TabIndex = 11; // Tab index
                                           // 
                                           // Configure DateTimePicker for filter date selection
                                           // 
            dtpFilterDate.Location = new Point(171, 22); // Sets DateTimePicker location
            dtpFilterDate.Name = "dtpFilterDate"; // Unique name for DateTimePicker
            dtpFilterDate.Size = new Size(200, 23); // DateTimePicker size
            dtpFilterDate.TabIndex = 12; // Tab index
                                         // 
                                         // Configure button for filtering and displaying selected data
                                         // 
            bFilter.Location = new Point(5, 51); // Sets button location
            bFilter.Name = "bFilter"; // Unique name for button
            bFilter.Size = new Size(160, 46); // Button size
            bFilter.TabIndex = 13; // Tab index
            bFilter.Text = "Display Selected Data"; // Text displayed on button
            bFilter.UseVisualStyleBackColor = true; // Uses the default button style
            bFilter.Click += bFilter_Click; // Click event for button
                                            // 
                                            // Configure GroupBox for filtering
                                            // 
            groupBoxFiltering.Controls.Add(bReceived); // Adds button for displaying received data
            groupBoxFiltering.Controls.Add(bFilter); // Adds filter button
            groupBoxFiltering.Controls.Add(dtpFilterDate); // Adds DateTimePicker for date selection
            groupBoxFiltering.Controls.Add(cbFilterPatient); // Adds ComboBox for patient selection
            groupBoxFiltering.Location = new Point(479, 298); // Sets GroupBox location
            groupBoxFiltering.Name = "groupBoxFiltering"; // Unique name for GroupBox
            groupBoxFiltering.Size = new Size(379, 156); // GroupBox size
            groupBoxFiltering.TabIndex = 14; // Tab index
            groupBoxFiltering.TabStop = false; // Disables tab stop for GroupBox
            groupBoxFiltering.Text = "Filtering"; // Text displayed on GroupBox
                                                  // 
                                                  // Configure button for displaying received data
                                                  // 
            bReceived.Location = new Point(6, 103); // Sets button location
            bReceived.Name = "bReceived"; // Unique name for button
            bReceived.Size = new Size(159, 47); // Button size
            bReceived.TabIndex = 14; // Tab index
            bReceived.Text = "Display Received Data"; // Text displayed on button
            bReceived.UseVisualStyleBackColor = true; // Uses the default button style
            bReceived.Click += bReceive_Click; // Click event for button
                                               // 
                                               // Configure GroupBox for the data section (start/stop, period, etc.)
                                               // 
            groupBoxData.Controls.Add(label3); // Adds additional label for the period between samples
            groupBoxData.Controls.Add(label2); // Adds label for time period
            groupBoxData.Controls.Add(tbTimerPeriod); // Adds TextBox for timer period
            groupBoxData.Controls.Add(bStopPumping); // Adds button for stopping monitoring
            groupBoxData.Controls.Add(label1); // Adds label for patient code
            groupBoxData.Controls.Add(bStartPumping); // Adds button for starting monitoring
            groupBoxData.Controls.Add(cbPatientCodeStart); // Adds ComboBox for patient selection
            groupBoxData.Location = new Point(485, 11); // Sets GroupBox location
            groupBoxData.Name = "groupBoxData"; // Unique name for GroupBox
            groupBoxData.Size = new Size(373, 131); // GroupBox size
            groupBoxData.TabIndex = 15; // Tab index
            groupBoxData.TabStop = false; // Disables tab stop for GroupBox
            groupBoxData.Text = "Data"; // Text displayed on GroupBox
                                        // 
                                        // Configure RadioButton for sending data over TCP/IP
                                        // 
            radioButton1.AutoSize = true; // Sets text auto-sizing
            radioButton1.Location = new Point(4, 84); // Sets RadioButton location
            radioButton1.Name = "radioButton1"; // Unique name for RadioButton
            radioButton1.Size = new Size(160, 19); // RadioButton size
            radioButton1.TabIndex = 15; // Tab index
            radioButton1.TabStop = true; // Sets RadioButton as selectable
            radioButton1.Text = "Send also through TCP/IP\r\n"; // Text displayed on RadioButton
            radioButton1.UseVisualStyleBackColor = true; // Uses the default RadioButton style
            radioButton1.CheckedChanged += radioButton1_CheckedChanged; // Selection changed event
                                                                        // 
                                                                        // Configure RadioButton for local option
                                                                        // 
            radioButton2.AutoSize = true; // Sets text auto-sizing
            radioButton2.Location = new Point(5, 37); // Sets RadioButton location
            radioButton2.Name = "radioButton2"; // Unique name for RadioButton
            radioButton2.Size = new Size(53, 19); // RadioButton size
            radioButton2.TabIndex = 16; // Tab index
            radioButton2.TabStop = true; // Sets RadioButton as selectable
            radioButton2.Text = "Local"; // Text displayed on RadioButton
            radioButton2.UseVisualStyleBackColor = true; // Uses the default RadioButton style
            radioButton2.CheckedChanged += radioButton2_CheckedChanged; // Selection changed event
                                                                        // 
                                                                        // Configure TextBox for entering server IP address
                                                                        // 
            textBox1.Location = new Point(194, 80); // Sets TextBox location
            textBox1.Name = "textBox1"; // Unique name for TextBox
            textBox1.Size = new Size(167, 23); // TextBox size
            textBox1.TabIndex = 17; // Tab index
            textBox1.Text = "192.168.0.105"; // Default text displayed in TextBox
                                             // 
                                             // Configure label for server IP address
                                             // 
            label5.AutoSize = true; // Sets text auto-sizing
            label5.Location = new Point(243, 56); // Sets label location
            label5.Name = "label5"; // Unique name for label
            label5.Size = new Size(52, 15); // Label size
            label5.TabIndex = 18; // Tab index
            label5.Text = "Server IP"; // Text displayed on label
                                       // 
                                       // Configure GroupBox for communication channel
                                       // 
            groupBox1.Controls.Add(radioButton1); // Adds RadioButton for TCP/IP
            groupBox1.Controls.Add(label5); // Adds label for IP address
            groupBox1.Controls.Add(radioButton2); // Adds RadioButton for local option
            groupBox1.Controls.Add(textBox1); // Adds TextBox for IP address
            groupBox1.Location = new Point(480, 478); // Sets GroupBox location
            groupBox1.Name = "groupBox1"; // Unique name for GroupBox
            groupBox1.Size = new Size(378, 128); // GroupBox size
            groupBox1.TabIndex = 19; // Tab index
            groupBox1.TabStop = false; // Disables tab stop for GroupBox
            groupBox1.Text = "Communication channel"; // Text displayed on GroupBox
            groupBox1.Enter += groupBox1_Enter; // Event for entering GroupBox
                                                // 
                                                // Main configuration of the DataPresentation form
                                                // 
            BackColor = SystemColors.ActiveCaption; // Sets background color a formularului
            ClientSize = new Size(868, 618); // Sets form size
            Controls.Add(groupBox1); // Adds GroupBox for communication channel
            Controls.Add(groupBoxData); // Adds GroupBox for the data section
            Controls.Add(groupBoxFiltering); // Adds GroupBox for filtering
            Controls.Add(label4); // Adds label for alarms area
            Controls.Add(richTextBox1); // Adds RichTextBox for displaying alarms
            Controls.Add(dgSensorBaseList); // Adds DataGridView for displaying sensor data
            Name = "DataPresentation"; // Unique name for form
            ((System.ComponentModel.ISupportInitialize)sensorBaseBindingSource).EndInit(); // Finalizes initialization of data source
            ((System.ComponentModel.ISupportInitialize)sensorBaseBindingSource1).EndInit(); // Finalizes initialization of second data source
            ((System.ComponentModel.ISupportInitialize)dgSensorBaseList).EndInit(); // Finalizes initialization of DataGridView
            groupBoxFiltering.ResumeLayout(false); // Resumes layout for filtering GroupBox
            groupBoxData.ResumeLayout(false); // Resumes layout for data GroupBox
            groupBoxData.PerformLayout(); // Applies layout for controls in data GroupBox
            groupBox1.ResumeLayout(false); // Resumes layout for communication GroupBox
            groupBox1.PerformLayout(); // Applies layout for controls in communication GroupBox
            ResumeLayout(false); // Resumes the form general layout
            PerformLayout(); // Applies layout for all controls
                             // Additional component initialization code can be added here
        }
        #endregion
        private BindingSource sensorBaseBindingSource; // Binding source for SensorBase objects
        private ComboBox cbPatientCodeStart; // ComboBox for selecting patient code
        private Button bStartPumping; // Button for starting monitoring
        private Button bStopPumping; // Button for stopping monitoring
        private BindingSource sensorBaseBindingSource1; // Second binding source for SensorBase objects
        private DataGridView dgSensorBaseList; // DataGridView for displaying sensor data
        private DataGridViewTextBoxColumn patientCodeDataGridViewTextBoxColumn1; // Column for patient code
        private DataGridViewTextBoxColumn sensorTypeDataGridViewTextBoxColumn1; // Column for sensor type
        private DataGridViewTextBoxColumn valueDataGridViewTextBoxColumn1; // Column for sensor value
        private DataGridViewTextBoxColumn timestampDataGridViewTextBoxColumn1; // Column for timestamp
        private TextBox tbTimerPeriod; // TextBox for setting the timer period
        private Label label2; // Label for time period
        private Label label3; // Additional label for period between samples
        private RichTextBox richTextBox1; // RichTextBox for displaying alarms
        private Label label4; // Label for the alarms area
        private ComboBox cbFilterPatient; // ComboBox for filtering data by patient
        private DateTimePicker dtpFilterDate; // Control for selecting the filter date
        private Button bFilter; // Button for filtering and displaying selected data
        private GroupBox groupBoxFiltering; // GroupBox for the data filtering section
        private GroupBox groupBoxData; // GroupBox for data management section
        private Button bReceived; // Button for displaying received data
        private RadioButton radioButton1; // RadioButton for sending data over TCP/IP
        private RadioButton radioButton2; // RadioButton for local option
        private TextBox textBox1; // TextBox for entering server IP address
        private Label label5; // Label for server IP address
        private GroupBox groupBox1; // GroupBox for communication channel options
    }
}
